---
# tasks file for config_drift
- name: configure acl settings
  ios_config:
    lines:
      - 10 permit ip host 192.0.2.1 any log
      - 20 permit ip host 192.0.2.2 any log
      - 30 permit ip host 192.0.2.3 any log
      - 40 permit ip host 192.0.2.4 any log
      - 50 permit ip host 192.0.2.5 any log
    parents: ip access-list extended test
    before: no ip access-list extended test
    match: exact
  check_mode: true
  register: changeFlag

- name: look at changeFlag
  debug:
    var: changeFlag

- name: SERVICENOW IF CHANGED
  block:
    - name: CREATE AN INCIDENT
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: incident
        data:
          short_description: "CONFIG OUT OF COMPLIANCE ON {{inventory_hostname}}"
          severity: 3
          priority: 2
          caller_id: "System Administrator"
          comments: "The configuration:\n--------\n {% for item in changeFlag.updates %}{{item}}\n{% endfor %}\n--------\n is missing on {{inventory_hostname}}"
      register: snow_var
      delegate_to: localhost

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.number
  when: changeFlag.changed