---
# tasks file for config_drift
- name: check banner settings
  ios_banner:
    banner: login
    text: |
      UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED
      You must have explicit, authorized permission to access or configure this device.
      Unauthorized attempts and actions to access or use this system may result in civil and/or 
      criminal penalties.
      All activities performed on this device are logged and monitored.
    state: present
  register: banner
  check_mode: "{{ task_check_mode }}"

- name: look at changeFlag
  debug:
    var: banner
