---
# tasks file for config_drift
- name: check banner settings
  ios_command:
    commands:
      - show banner login
  register: banner

- name: look at changeFlag
  debug:
    var: banner.stdout[0]

- name: SERVICENOW IF CHANGED
  block:
    - name: CREATE AN INCIDENT
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: incident
        data:
          short_description: "CONFIG OUT OF COMPLIANCE ON {{inventory_hostname}}"
          severity: 3
          priority: 2
          caller_id: "System Administrator"
          comments: "The configuration:\n--------\n banner login\n--------\n is missing on {{inventory_hostname}}"
      register: snow_var
      delegate_to: localhost

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.number
  when: not banner.stdout[0]